### ISSUE TITLE
Hmac

### ISSUE THREAD

**Issue by arj03** [ssb-ngi-pointer/ssb-bendy-butt#4]
Add hmac support

**Comment by arj03** [comment]
Go support for this for [reference](https://github.com/ssb-ngi-pointer/go-metafeed/commit/d3748eb648ab196c5fcfae80f99dc3529d152d2e)

**Comment by cryptix** [comment]
Here is the more approachable [documentation version]( https://pkg.go.dev/github.com/ssb-ngi-pointer/go-metafeed@v0.0.0-20210715094956-e2d13ec3b587/internal/sign), which also links to the code.
